account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('signup/', views.UserCreateAndLoginView.as_view(), name='signup'),
    
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='account/login.html'
    ), name='login'),
    
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('detail_user/<int:pk>/', views.UserDetail.as_view(), name='detail_user'),
    
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='edit_user'),
    
    path('change_password/', views.PasswordChange.as_view(), name='change_password'),
    
    path('delete_user/<int:pk>/', views.UserDelete.as_view(), name='delete_user'),
]

loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('account/', include('account.urls')),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

account/models.py
from django.db import models

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
    )
    email = models.EmailField(
        _('email address'),
        unique=True,
    )
    age = models.PositiveIntegerField(_('edad'), default=0, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'age')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )

tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='Título', max_length=255)  
    content = forms.CharField(label='Contenido', widget=forms.Textarea())  

account/views.py
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate, get_user_model
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.mixins import UserPassesTestMixin
from .forms import CustomUserCreationForm, UserUpdateForm
from django.contrib.auth.views import LogoutView

User = get_user_model()

class UserCreateAndLoginView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "account/signup.html"
    success_url = reverse_lazy("tasks:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data.get("email")
        raw_pw = form.cleaned_data.get("password1")
        user = authenticate(email=email, password=raw_pw)
        if user is not None:
            login(self.request, user)
        else:
            form.add_error(None, "Error en la autenticación.")
        return response

class OnlyYouMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class UserDetail(OnlyYouMixin, DetailView):
    model = User
    template_name = 'account/detail_user.html'

class UserUpdate(OnlyYouMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'account/edit_user.html'

    def get_success_url(self):
        return reverse_lazy('detail_user', kwargs={'pk': self.kwargs['pk']})

class PasswordChange(PasswordChangeView):
    template_name = 'account/change_password.html'
    def get_success_url(self):
        return reverse_lazy('detail_user', kwargs={'pk': self.request.user.pk})

class UserDelete(OnlyYouMixin, DeleteView):
    model = User
    template_name = 'account/delete_user.html'
    success_url = reverse_lazy('login')

class UserLogout(LogoutView):
    next_page = reverse_lazy('login')

tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm


def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Registro de Tareas</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Registrar">
</form>

<br>

<a href="{% url 'tasks:index' %}">Volver</a>
{% endblock %}

tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Eliminación de Tareas</h1>
<p>
  <strong>Título:</strong>
  {{task.title}}
</p>

<p>
  <strong>Contenido:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Eliminar">
</form>

<br>

<a href="{% url 'tasks:index' %}">Volver</a>
{% endblock %}

tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Detalles de la Tarea</h1>
<p>
  <strong>Título:</strong>
  {{task.title}}
</p>

<p>
  <strong>Contenido:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">Volver</a> |
<a href="{% url 'tasks:edit' task.id %}">Editar</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Edición de Tareas</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Actualizar">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">Detalles</a> |
<a href="{% url 'tasks:index' %}">Volver</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>Lista de Tareas</h1>
<table>
  <tr>
    <th>Título</th>
    <th>Contenido</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">Detalles</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">Editar</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">Eliminar</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">Crear Nuevo</a>

{% endblock %}

templates/base.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Task</title>
    <link rel="stylesheet" href="{% static 'tasks/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">
  </head>

  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'tasks:index' %}">Lista de tareas</a></li>
        <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
        <li><a href="{% url 'detail_user' user.pk %}">Información del miembro</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Acceso a la cuenta</a></li>
        <li><a href="{% url 'signup' %}">Registro de cuenta</a></li>
        {% endif %}
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>

</html>